<?php
/**
 * Created by PhpStorm.
 * User: lee
 * Date: 2018/8/3
 * Time: 13:55
 */

namespace elilee\wx\user;


use elilee\wx\accessToken\AccessToken;
use elilee\wx\core\Driver;
use elilee\wx\core\Exception;

class Remark extends Driver
{
    const API_UPDATE_REMARK_URL = "https://api.weixin.qq.com/cgi-bin/user/info/updateremark?access_token=";

    private $accessToken;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->accessToken = (new AccessToken(['conf'=>$this->conf,'httpClient'=>$this->httpClient]))->getToken();
    }

    public function update($openId, $remark){
        $this->httpClient->formatters = ['uncodeJson'=>'elilee\wx\helper\JsonFormatter'];

        $response = $this->httpClient->createRequest()
            ->setUrl(self::API_UPDATE_REMARK_URL.$this->accessToken)
            ->setMethod('post')
            ->setData([
                'openid'=>$openId,
                'remark'=>$remark
            ])
            ->setFormat('uncodeJson')
            ->send();
        $data = $response->getData();
        if(isset($data['errcode']) && $data['errcode'] ==0){
            return true;
        }else{
            throw new Exception($data['errmesg'],$data['errcode']);
        }
    }

}